sudo: false

language: android

env:
  - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - openssl aes-256-cbc -d -a -k "$encription_password" -in app/gradle.properties.enc -out app/gradle.properties
  - openssl aes-256-cbc -d -a -k "$encription_password" -in app/service-account.p12.enc -out app/service-account.p12
  - openssl aes-256-cbc -d -a -k "$encription_password" -in app/keystore.jks.enc -out app/keystore.jks
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - travis_retry travis_wait ./gradlew assembleDebug

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - travis_wait ./gradlew test
  - travis_wait ./gradlew connectedDebugAndroidTest

after_script:
  - adb logcat -d
